name: JOQUER-GA
services:
  - name: JOQUER-GA
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin


      
